flags=-O2 -Wall -std=c2x -I../osapi
ldflags=

.PHONY: clean clean-osapi

all: clean clean-osapi command.com

../osapi/osapi.so: ../osapi/osapi.c ../osapi/osapi.h ../osapi/disk.c ../osapi/disk.h
	$(MAKE) -C ../osapi -sk "CFLAGS=$(flags)"

command.com:command.o ../osapi/osapi.so
	cc $(flags) $^ -o $@ $(ldflags)

command.o:command.c command.h
	cc $(flags) -c $<

clean-osapi:
	cd ../osapi
	${MAKE} clean

clean:
	rm -f *.o command.com ../osapi/*.o ../osapi/*.so 
